target 'LearnRxSwift' do
  use_frameworks!
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
end

target 'LearnRxSwiftTests' do
  use_frameworks!
  pod 'RxBlocking', '~> 4.0'
  pod 'RxTest', '~> 4.0'
end